### ISSUE TITLE
Feedback on 'Serve a local file'

### ISSUE THREAD

**Issue by skilganon** [node-red/cookbook.nodered.org#6]
Where do I find the "File In" node ? 
I'm running on Bluemix so I guess its not available there. I used Dropbox as an alternative which works fine

**Comment by dceejay** [comment]
we prefer general usage questions via the mailing list or slack channel (links on http://nodered.org )
But you are correct - there is no concept of a file system on your cloud (or rather not one that is persistent over a re-deploy) so the file node is not there.

**Comment by knolleary** [comment]
Just to clarify. You do of course have a filesystem on Bluemix. But, if you dynamically write a file to it from your app, it will get lost the next time your application restarts. That is why we removed the `File Out` node on Bluemix. Unfortunately, due to the way the nodes are structured, the `File In` node got removed with it.

So it depends exactly what you want to do.

The Bluemix instance of node-red is already configured to serve static files out of the `public` directory - so you can add files there (via devOps services, or cf push).

Alternatively, you could edit the `bluemix-settings.js` (via devops services etc) and remove `'50-file.js'` from the `nodesExcludes` settings - that will restore the file node to your instance.
